// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/articles": {
            "get": {
                "description": "ListBlocks articles by list parameters",
                "tags": [
                    "Article"
                ],
                "summary": "ListBlocks Articles",
                "operationId": "list-articles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Info JWT",
                        "name": "X-USER-JWT",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "example": false,
                        "name": "desc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "id",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 20,
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/viewmodels.Article"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a batch of articles",
                "tags": [
                    "Article"
                ],
                "summary": "Update Article",
                "operationId": "update-article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Info JWT",
                        "name": "X-USER-JWT",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update parameters.",
                        "name": "Article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inputmodels.UpdateArticle"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success."
                    },
                    "404": {
                        "description": "Not found.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a batch of articles",
                "tags": [
                    "Article"
                ],
                "summary": "Create Article",
                "operationId": "create-articles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Info JWT",
                        "name": "X-USER-JWT",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "CreateArticles",
                        "name": "Item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inputmodels.CreateArticle"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success."
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a batch of articles",
                "tags": [
                    "Article"
                ],
                "summary": "Delete Article",
                "operationId": "delete-article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Info JWT",
                        "name": "X-USER-JWT",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Success."
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "404": {
                        "description": "Not found.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    }
                }
            }
        },
        "/articles/{id}": {
            "get": {
                "description": "GetBlock article by ID",
                "tags": [
                    "Article"
                ],
                "summary": "GetBlock Article",
                "operationId": "get-article",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Info JWT",
                        "name": "X-USER-JWT",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Article"
                        }
                    },
                    "404": {
                        "description": "Not found.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    },
                    "500": {
                        "description": "Internal error.",
                        "schema": {
                            "$ref": "#/definitions/viewmodels.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "inputmodels.CreateArticle": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "文章名稱",
                    "type": "string"
                },
                "no": {
                    "description": "文章代號(unique)",
                    "type": "string"
                },
                "quick_code": {
                    "description": "簡碼",
                    "type": "string"
                }
            }
        },
        "inputmodels.ListParam": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "boolean",
                    "example": false
                },
                "order": {
                    "type": "string",
                    "example": "id"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "per_page": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "inputmodels.UpdateArticle": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "流水號",
                    "type": "integer"
                },
                "name": {
                    "description": "文章名稱",
                    "type": "string"
                },
                "no": {
                    "description": "文章代號(unique)",
                    "type": "string"
                },
                "quick_code": {
                    "description": "簡碼",
                    "type": "string"
                }
            }
        },
        "viewmodels.Article": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "建檔日期",
                    "type": "string"
                },
                "id": {
                    "description": "流水號",
                    "type": "integer"
                },
                "name": {
                    "description": "文章名稱",
                    "type": "string"
                },
                "no": {
                    "description": "文章代號(unique)",
                    "type": "string"
                },
                "quick_code": {
                    "description": "簡碼",
                    "type": "string"
                },
                "updated_at": {
                    "description": "修改日期",
                    "type": "string"
                }
            }
        },
        "viewmodels.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "System Main Data",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
