definitions:
  inputmodels.ListBlocksParam:
    properties:
      limit:
        description: Limit
        type: integer
    type: object
  viewmodels.Error:
    properties:
      code:
        type: integer
      error:
        type: object
      message:
        type: string
    type: object
  viewmodels.GetSingleBlock:
    properties:
      block_hash:
        type: string
      block_num:
        type: integer
      block_time:
        type: string
      parent_hash:
        type: string
      transactions:
        items:
          type: string
        type: array
    type: object
  viewmodels.GetTransaction:
    properties:
      block_hash:
        type: string
      data:
        type: string
      from:
        type: string
      logs:
        items:
          $ref: '#/definitions/viewmodels.TransactionLog'
        type: array
      nonce:
        type: integer
      to:
        type: string
      tx_hash:
        type: string
      value:
        type: string
    type: object
  viewmodels.ListBlockItem:
    properties:
      block_hash:
        type: string
      block_num:
        type: integer
      block_time:
        type: string
      parent_hash:
        type: string
    type: object
  viewmodels.ListBlocks:
    properties:
      blocks:
        items:
          $ref: '#/definitions/viewmodels.ListBlockItem'
        type: array
    type: object
  viewmodels.TransactionLog:
    properties:
      data:
        type: string
      index:
        type: integer
      tx_hash:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: System Main Data
paths:
  /blocks:
    get:
      description: ListBlocks blocks by list parameters
      operationId: list-blocks
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: Success.
          schema:
            $ref: '#/definitions/viewmodels.ListBlocks'
        "500":
          description: Internal error.
          schema:
            $ref: '#/definitions/viewmodels.Error'
      summary: ListBlocks Blocks
      tags:
      - Block
  /blocks/{block_num}:
    get:
      description: Get block by block number
      operationId: get-block
      parameters:
      - description: Block Number
        in: path
        name: block_num
        required: true
        type: string
      responses:
        "200":
          description: Success.
          schema:
            $ref: '#/definitions/viewmodels.GetSingleBlock'
        "404":
          description: Not found.
          schema:
            $ref: '#/definitions/viewmodels.Error'
        "500":
          description: Internal error.
          schema:
            $ref: '#/definitions/viewmodels.Error'
      summary: Get Block
      tags:
      - Block
  /transaction/{tx_hash}:
    get:
      description: GetBlock block by block number
      operationId: get-transaction
      parameters:
      - description: transaction hash
        in: path
        name: tx_hash
        required: true
        type: string
      responses:
        "200":
          description: Success.
          schema:
            $ref: '#/definitions/viewmodels.GetTransaction'
        "404":
          description: Not found.
          schema:
            $ref: '#/definitions/viewmodels.Error'
        "500":
          description: Internal error.
          schema:
            $ref: '#/definitions/viewmodels.Error'
      summary: Get Transaction
      tags:
      - Transaction
swagger: "2.0"
